#pragma once

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the even-valued terms.

*/
namespace Challange
{
	template<class T>
	class Day2 : public Days<T>
	{
	public:
		virtual ~Day2() {}
		Day2() {}
		T doChallange(const char* fmt, ...) override;

	private:
		Day2(const Day2&) = delete; // not implemented copy-constructor
		const Day2& operator=(const Day2&) = delete; // not implemented copy assigment
	};
}